### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by dbolotin** [milaboratory/github-ci#2]
- [x] MiLib
- [x] [repseqio/repseqio](https://github.com/repseqio/repseqio)
- [x] MiXCR

**Comment by dbolotin** [comment]
@DenKoren 
https://github.community/t/how-to-allow-unauthorised-read-access-to-github-packages-maven-repository/115517
It seems that GitHub Packages is not a solution for Public Maven Repository after all.
😐

**Comment by DenKoren** [comment]
MiLib seems to be ready. The only thing not tested yet is publication to Sonatype.
- Long tests work;
- Test reports upload works;
- 'Tests ended' notification works;
- 'Waiting for review' notification works (before new release creation);

**Comment by DenKoren** [comment]
MiXCR seems to be ready:
- integration tests work;
- custom test hooks for test data preparation works;
- binary upload to S3 works;
- hash in binary name for dev releases works;

**Comment by DenKoren** [comment]
Added test data cache/restore for integration and unit tests downloaded by shell scripts.
